### ISSUE TITLE
Add option to attach logos for startups

### ISSUE THREAD

**Issue by Suuuuha** [UKITH/Arabs-Startups#151]

**Comment by Karyum** [comment]
@esraajb would you use amazon s3 ?? if not it's mongo/mongoose and would you use GRIDfs in mongo??
or just store it as a buffer?

**Comment by esraajb** [comment]
Best option is s3 as storing in mongodb would slow the website. 
Do you think you can do s3?

**Comment by Karyum** [comment]
yup did it before. but the only issue is that if i want to make an account i need a credit card :grimacing:

**Comment by esraajb** [comment]
They don't charge for that, so you can add yours as it's your account.
