### ISSUE TITLE
Typos on main page

### ISSUE THREAD

**Issue by JWLD** [UKITH/Arabs-Startups#164]
Noticed these when I checked it out earlier and thought you might want to correct them before Weds!

Enter a keyword. and/or -> Enter a keyword. And/or
Enterprenurs -> Entrepreneurs
under-represented -> underrepresented
due to lack of -> due to a lack of
dunding -> funding
stereotypes.Fortunately -> stereotypes. Fortunately
up tp 100 words -> up to 100 words

Also spaces before question marks looks a bit odd in English - not sure if it's that way in Arabic or sth?

**Comment by JWLD** [comment]
@Suuuuha @Karyum

**Comment by Suuuuha** [comment]
@JWLD cheers mate..appreciated :black_heart:
