### ISSUE TITLE
implement view for submission page

### ISSUE THREAD

**Issue by Suuuuha** [UKITH/Arabs-Startups#20]
Implement a submission form containing: 
- [x] Founder name 
- [x] Startup Name (should be unique)
- [x] Phone number
- [x] E-mail
- [x] Field (drop down list)
- [x] Startup stage (drop down list)
- [x] photo (e.g startup logo)

**Comment by Karyum** [comment]
- [ ] Description
- [ ]  social media links
- [ ] website link
