### ISSUE TITLE
Results Page Checkboxes to Dropdown

### ISSUE THREAD

**Issue by Karyum** [UKITH/Arabs-Startups#77]
Change the results page sector checkboxes to dropdown list

**Comment by Karyum** [comment]
@esraajb it isn't supposed to be a dropdown list it's supposed to be a list of checkboxes
close this issue if you agree

**Comment by esraajb** [comment]
@Karyum you can close an issue you opened

**Comment by Karyum** [comment]
@esraajb yeah I know but i just wanted to know your opinion
